Updated backup

diff --git a/.bin/crun b/.bin/crun
--- a/.bin/crun
+++ b/.bin/crun
@@ -1,8 +1,17 @@
 # Takes one C++ source file as input it compiles it and runs it
 echo "Building $1..."
-g++ $1 -o o${1%.*} --std=c++14 -Wall -O2 -Wextra -pedantic
+g++ $1 -o o${1%.*} --std=c++14 -Wall -O3 -Wextra -pedantic
 
-if [ -f o${1%.*} ]; then
-  echo "Running o${1%.*}..."
- ./o${1%.*}
+RET=$?
+
+if [[ $RET == 0 ]]; then
+  if [ -f o${1%.*} ]; then
+    echo "Running o${1%.*}..."
+    time ./o${1%.*}
+  else
+    echo "No compiled file found."
+  fi
+else
+  echo "Compiling failed."
+  exit $RET
 fi
